name: Deploy Frontend to Softrealizer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
      VITE_APP_ACCESS_KEY: ${{ secrets.VITE_APP_ACCESS_KEY }}
      VITE_APP_SECRET_KEY: ${{ secrets.VITE_APP_SECRET_KEY }}
      VITE_APP_REFRESH_KEY: ${{ secrets.VITE_APP_REFRESH_KEY }}
      VITE_APP_PAGE_SIZE: ${{ secrets.VITE_APP_PAGE_SIZE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      VITE_APP_S3_URL: ${{ secrets.VITE_APP_S3_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install Dependencies and Build (Local Runner)
        working-directory: ./client
        run: |
          echo "Local build: Cleaning up previous build..."
          rm -rf dist
          npm cache clean --force
          npm install
          npm run build
          echo "Local dist folder contents:"
          ls -la dist

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.AWS_MUSCO_STORE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # Change to the client directory on the server
            cd ~/mcStore/client

            echo "Server: Resetting repo and pulling latest changes..."
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            echo "Server: Cleaning previous build and installing dependencies..."
            rm -rf dist
            npm cache clean --force
            npm install

            echo "Server: Environment variables:"
            echo "VITE_APP_API_URL is $VITE_APP_API_URL"
            # (Print any other needed variables)

            echo "Server: Starting build..."
            npm run build

            # Ensure the dist folder exists (create it if missing)
            mkdir -p dist

            echo "Server: Final dist folder contents:"
            ls -la dist

            # Check if any build files exist
            if [ "$(ls -A dist)" ]; then
              echo "Build files found in dist."
            else
              echo "No build files found in dist! Exiting."
              exit 1
            fi

            # Remove old files from the deployment directory
            echo "Cleaning deployment directory..."
            sudo rm -rf /var/www/softrealizer/*

            # Deploy the new build by copying build files from dist
            echo "Deploying new build..."
            sudo cp -r /home/ubuntu/mcStore/client/dist/* /var/www/softrealizer/

            # Set proper ownership so nginx can serve the files
            sudo chown -R www-data:www-data /var/www/softrealizer

            echo "Updated /var/www/softrealizer contents:"
            sudo ls -la /var/www/softrealizer

            # Reload nginx and restart the Node.js app
            sudo systemctl reload nginx
            pm2 restart all
