name: Deploy Frontend to Softrealizer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23" # use node version compatible with your app

      - name: Install Dependencies and Build
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.AWS_MUSCO_STORE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd ~/mcStore/client

            # Reset and fetch the latest code
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            # Install all dependencies and build
            npm install
            npm run build

            sudo rm -rf /var/www/softrealizer/*
            sudo rm -rf /var/www/softrealizer/.*

            # Deploy new build
            sudo cp -R dist/* /var/www/softrealizer/

            # Reload nginx and restart node app
            sudo systemctl reload nginx
            pm2 restart all
