name: Deploy Frontend to Softrealizer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies and Build (Client)
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.AWS_MUSCO_STORE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # Go to project directory
            cd /home/ubuntu/mcStore

            # Force sync to GitHub to prevent merge conflicts
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            # Install dependencies and build
            cd client
            npm install --production
            npm run build

            # Copy to web server directory
            sudo cp -R ./dist/* /var/www/softrealizer/

            # Reload Nginx and restart pm2
            sudo systemctl reload nginx
            pm2 restart all
